// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"fmt"
	"io"
	"strconv"

	"github.com/Shridhar2104/logilo/graphql/models"
)

type AccountInput struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Accounts struct {
	Orders []*models.Order `json:"orders"`
}

type BankAccount struct {
	UserID          string `json:"userId"`
	AccountNumber   string `json:"accountNumber"`
	BeneficiaryName string `json:"beneficiaryName"`
	IfscCode        string `json:"ifscCode"`
	BankName        string `json:"bankName"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}

type BankAccountInput struct {
	AccountNumber   string `json:"accountNumber"`
	BeneficiaryName string `json:"beneficiaryName"`
	IfscCode        string `json:"ifscCode"`
	BankName        string `json:"bankName"`
}

type Customer struct {
	ID        *string `json:"id,omitempty"`
	Email     *string `json:"email,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Phone     *string `json:"phone,omitempty"`
}

type Mutation struct {
}

type OrderConnection struct {
	Edges      []*OrderEdge `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type OrderEdge struct {
	Node   *models.Order `json:"node"`
	Cursor string        `json:"cursor"`
}

type OrderFilter struct {
	CreatedAtStart    *string  `json:"createdAtStart,omitempty"`
	CreatedAtEnd      *string  `json:"createdAtEnd,omitempty"`
	FinancialStatus   *string  `json:"financialStatus,omitempty"`
	FulfillmentStatus *string  `json:"fulfillmentStatus,omitempty"`
	MinTotalPrice     *float64 `json:"minTotalPrice,omitempty"`
	MaxTotalPrice     *float64 `json:"maxTotalPrice,omitempty"`
	SearchTerm        *string  `json:"searchTerm,omitempty"`
}

type OrderInput struct {
	AccountID string                `json:"accountId"`
	LineItems []*OrderLineItemInput `json:"lineItems"`
}

type OrderLineItemInput struct {
	ID          string  `json:"id"`
	Amount      float64 `json:"amount"`
	Description string  `json:"description"`
}

type OrderPaginationInput struct {
	Page     *int         `json:"page,omitempty"`
	PageSize *int         `json:"pageSize,omitempty"`
	Filter   *OrderFilter `json:"filter,omitempty"`
	Sort     *OrderSort   `json:"sort,omitempty"`
}

type OrderSort struct {
	Field     OrderSortField `json:"field"`
	Direction SortDirection  `json:"direction"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
	TotalPages      int     `json:"totalPages"`
	CurrentPage     int     `json:"currentPage"`
}

type PaginationInput struct {
	Skip int `json:"skip"`
	Take int `json:"take"`
}

type Query struct {
}

type OrderSortField string

const (
	OrderSortFieldCreatedAt   OrderSortField = "CREATED_AT"
	OrderSortFieldUpdatedAt   OrderSortField = "UPDATED_AT"
	OrderSortFieldOrderNumber OrderSortField = "ORDER_NUMBER"
	OrderSortFieldTotalPrice  OrderSortField = "TOTAL_PRICE"
)

var AllOrderSortField = []OrderSortField{
	OrderSortFieldCreatedAt,
	OrderSortFieldUpdatedAt,
	OrderSortFieldOrderNumber,
	OrderSortFieldTotalPrice,
}

func (e OrderSortField) IsValid() bool {
	switch e {
	case OrderSortFieldCreatedAt, OrderSortFieldUpdatedAt, OrderSortFieldOrderNumber, OrderSortFieldTotalPrice:
		return true
	}
	return false
}

func (e OrderSortField) String() string {
	return string(e)
}

func (e *OrderSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderSortField", str)
	}
	return nil
}

func (e OrderSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
